### ISSUE TITLE
Fails to build with HDF 4.4.0

### ISSUE THREAD

**Issue by sebastic** [PDLPorters/PDL-IO-HDF#1]
As reported in [Debian Bug #1146655](https://bugs.debian.org/1146655):
> Your package FTBFS with HDF 4.4.0:
> ```
> Warning (mostly harmless): No library found for -ldf
> Warning (mostly harmless): No library found for -ldf
> [...]
> VS.xs: In function 'XS_PDL__IO__HDF__VS__Vgetname':
> VS.xs:789:21: error: implicit declaration of function 'Vgetnamelen'; did you mean 'SDgetnamelen'? [-Wimplicit-function-declaration]
>   789 |                 if (Vgetnamelen(vgroup_id, &len)) croak("Failed to get Vgetnamelen for ID=%d", vgroup_id);
>       |                     ^~~~~~~~~~~
>       |                     SDgetnamelen
> VS.xs:791:17: error: too few arguments to function 'Vgetname'; expected 3, have 2
>   791 |                 Vgetname(vgroup_id,vgroup_name);
>       |                 ^~~~~~~~
> In file included from /usr/include/hdf/hdf.h:192,
>                  from VS.xs:24:
> /usr/include/hdf/hproto.h:1405:15: note: declared here
>  1405 | HDFLIBAPI int Vgetname(int32 vkey, char *vgname, size_t *buf_size);
>       |               ^~~~~~~~
> VS.xs: In function 'XS_PDL__IO__HDF__VS__Vgetclass':
> VS.xs:811:21: error: implicit declaration of function 'Vgetclassnamelen' [-Wimplicit-function-declaration]
>   811 |                 if (Vgetclassnamelen(vgroup_id, &len)) croak("Failed to get Vgetclassnamelen for ID=%d", vgroup_id);
>       |                     ^~~~~~~~~~~~~~~~
> VS.xs:813:17: error: too few arguments to function 'Vgetclass'; expected 3, have 2
>   813 |                 Vgetclass(vgroup_id,vgroup_class);
>       |                 ^~~~~~~~~
> /usr/include/hdf/hproto.h:1407:15: note: declared here
>  1407 | HDFLIBAPI int Vgetclass(int32 vkey, char *vgclass, size_t *buf_size);
>       |               ^~~~~~~~~
> ```
> The full buildlog is attached.
> [libpdl-io-hdf-perl_2.004-2_amd64.build](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1146655;filename=libpdl-io-hdf-perl_2.004-2_amd64.build;msg=5)
>
> Note that libdf was renamed to libhdf in 4.4.0.
